### ISSUE TITLE
Docker 'pull image' is missing in DPT Jenkinsfile

### ISSUE THREAD

**Issue by stefanodallapalma** [radon-h2020/radon-cicd-templates#9]
In the [DPT Jenkinsfile](https://github.com/radon-h2020/radon-cicd-templates/blob/master/DPT/jenkins/Jenkinsfile) you are assuming that the `radon-dp:latest` image is already present on the machine. 
If this is the intended behavior, feel free to ignore and close this issue.
Otherwise, I guess a step should be added to pull the image from Dockerhub: `sh 'docker pull radonconsortium/radon-dp:latest'`.

**Comment by naesheim** [comment]
I think docker run implies docker pull if the image is not present?

**Comment by stefanodallapalma** [comment]
No, it might depend on what you use to run it. For example, what you said is true if using the Python library docker-py, but it's not if running a shell command.
In any case, specifying `docker run radon-dp:latest` does not imply pulling the image if not present. Indeed, the image could not be found as it should be `radonconsortium/radon-dp:latest`.

**Comment by naesheim** [comment]
So a fix would be an update at line 8 : 
DPT_DOCKER_NAME = 'radonconsortium/radon-dp:latest'

**Comment by naesheim** [comment]
fixed by #11
